#!/bin/sh

if [ "`basename $PWD`" = "compare" ]; then
    cd sml
fi

OS=`uname -s`
if [ "$OS" = "Linux" ]; then
  ulimit -s 1048576
  export TIME="0:RESULT-mem:kbyte: %M.0"
  DOIT=/usr/bin/time
fi

exec $DOIT ./sml_"$@"
