#!/bin/sh

ARGS=""
while [ "`expr \"x$1\" : \"x\(.\{2\}\)\"`" = "-A" ]; do
  ARGS="$ARGS `expr \"x$1\" : \"x.\{2\}\(.*\)\"`"
  shift
done

if [ "`basename $PWD`" = "compare" ]; then
    cd sml
fi

IMG=`ls sml_$1_image.*`
shift

exec sml $ARGS @SMLload=${IMG} "$@"
