#!/bin/sh

ARGS=""
while [ "${1:0:2}" = "-A" ]; do
  ARGS="$ARGS ${1:2}"
  shift
done

if [ "`basename $PWD`" = "compare" ]; then
    cd sml
fi

IMG=`ls sml_$1_image.*`
shift

exec sml $ARGS @SMLload=${IMG} "$@"
