#!/bin/sh

ARGS=""
while [ "`expr \"x$1\" : \"x\(.\{2\}\)\"`" = "-A" ]; do
  ARGS="$ARGS `expr \"x$1\" : \"x.\{2\}\(.*\)\"`"
  shift
done

if [ "`basename $PWD`" = "compare" ]; then
    cd racket
fi

FIL="./racket_$1.scm"
shift

if [ ! -h pycket ]; then
  exit 1
fi
PYCKET=pycket/../pycket-c
exec $PYCKET $ARGS $FIL "$@"
