#!/bin/sh
[ -n "$SHIELDED_RUNNER" ] && [ -z "$RUN_SHIELDED" ] && exec "$SHIELDED_RUNNER" "$0" "$@"
PROGRAM=`echo $0 | sed 's%.*/%%'`
PROGDIR="$(cd `dirname $0`; echo $PWD)"

PYCKET=$PROGDIR/pycket/pycket-c-shapes exec $PROGDIR/PYCKET_RUN "$@"
