#!/bin/sh

ARGS=""
while [ "${1:0:2}" = "-A" ]; do
  ARGS="$ARGS ${1:2}"
  shift
done

FIL="./racket_$1.scm"
shift

if [ ! -h pycket ]; then
  exit 1
fi
PYCKET=pycket/../pycket-c
exec $PYCKET $ARGS $FIL "$@"
