#!/bin/sh
[ -n "$SHIELDED_RUNNER" ] && [ -z "$RUN_SHIELDED" ] && exec "$SHIELDED_RUNNER" "$0" "$@"

ARGS=""
while [ "`expr \"x$1\" : \"x\(.\{2\}\)\"`" = "-A" ]; do
  ARGS="$ARGS `expr \"x$1\" : \"x.\{2\}\(.*\)\"`"
  shift
done

if [ "`basename $PWD`" = "compare" ]; then
    cd racket
fi

FIL="./racket_$1.scm"
shift

if [ ! -h pycket ]; then
  if [ -z "$PYCKET" ]; then
    exit 1
  fi
fi
PYCKET=${PYCKET:-pycket/../pycket-c}

if [ ! -z "${DO_PYPYLOG}" ]; then
  if [ "${PYCKET##*-}" -eq "c" ]; then
      OUT="${FIL%.*}-out.pypylog"
  else
      OUT="${FIL%.*}-${PYCKET##*-}-out.pypylog"
  fi
  rm -f ${FIL}-out.txt
  export PYPYLOG=${DO_PYPYLOG}:${OUT}
fi

OS=`uname -s`
if [ "$OS" = "Linux" ]; then
  ulimit -s 1048576
  export TIME="0:RESULT-mem:kbyte: %M.0"
  DOIT=/usr/bin/time
fi

exec $DOIT $PYCKET $ARGS $FIL "$@"
