#!/bin/sh

ARGS=""
while [ "${1:0:2}" = "-A" ]; do
  ARGS="$ARGS ${1:2}"
  shift
done

if [ "`basename $PWD`" = "compare" ]; then
    cd racket
fi

FIL="./racket_$1.scm"
shift

exec racket $ARGS -r $FIL "$@"
