#!/bin/sh

ARGS=""
while [ "`expr \"x$1\" : \"x\(.\{2\}\)\"`" = "-A" ]; do
  ARGS="$ARGS `expr \"x$1\" : \"x.\{2\}\(.*\)\"`"
  shift
done

if [ "`basename $PWD`" = "compare" ]; then
    cd racket
fi

FIL="./racket_$1.scm"
shift

OS=`uname -s`
if [ "$OS" = "Linux" ]; then
  ulimit -s 1048576
  export TIME="RESULT-mem: %M"
  DOIT=/usr/bin/time
fi

exec $DOIT racket $ARGS -r $FIL "$@"
