#!/bin/sh
[ -n "$SHIELDED_RUNNER" ] && [ -z "$RUN_SHIELDED" ] && exec "$SHIELDED_RUNNER" "$0" "$@"

ARGS="-E -s 99999999 -w 0"
while [ "`expr \"x$1\" : \"x\(.\{2\}\)\"`" = "-A" ]; do
  ARGS="$ARGS `expr \"x$1\" : \"x.\{2\}\(.*\)\"`"
  shift
done

FIL="$1.ship"
shift

if [ "`basename $PWD`" = "compare" ]; then
    cd theseus
fi

if [ ! -x theseus ]; then
  exit 1
fi
THESEUS=./theseus

OS=`uname -s`
if [ "$OS" = "Linux" ]; then
  ulimit -s 1048576
  export TIME="0:RESULT-mem:kbyte: %M.0"
  DOIT=/usr/bin/time
fi

rm -f $FIL.docked
$THESEUS -R $ARGS "$FIL" "$@" 2>&1 >/dev/null
export PYPY_GC_MIN=1GB
export PYPY_GC_GROWTH=2.5

exec $DOIT $THESEUS -W $ARGS "$FIL" "$@"
