#!/bin/sh

ARGS="-E"
while [ "${1:0:2}" = "-A" ]; do
  ARGS="$ARGS ${1:2}"
  shift
done

FIL="$1.lamb"
shift

if [ "`basename $PWD`" = "compare" ]; then
    cd lamb
fi

if [ ! -x lamb ]; then
  exit 1
fi
LAMB=./lamb



exec $LAMB -R -W $ARGS $FIL "$@"
