#!/bin/sh

ARGS="-E"
while [ "`expr \"x$1\" : \"x\(.\{2\}\)\"`" = "-A" ]; do
  ARGS="$ARGS `expr \"x$1\" : \"x.\{2\}\(.*\)\"`"
  shift
done

FIL="$1.lamb"
shift

if [ "`basename $PWD`" = "compare" ]; then
    cd lamb
fi

if [ ! -x lamb ]; then
  exit 1
fi
LAMB=./lamb

rm -f $FIL.lambc
$LAMB -R $ARGS "$FIL" "$@" 2>&1 >/dev/null
exec $LAMB -W $ARGS "$FIL" "$@"
