#!/bin/sh
[ -n "$SHIELDED_RUNNER" ] && [ -z "$RUN_SHIELDED" ] && exec "$SHIELDED_RUNNER" "$0" "$@"

ARGS="--silent --no-display"
while [ "`expr \"x$1\" : \"x\(.\{2\}\)\"`" = "-A" ]; do
  ARGS="$ARGS `expr \"x$1\" : \"x.\{2\}\(.*\)\"`"
  shift
done

if [ "x$RSQUEAK" = "x" ]; then
    RSQUEAK=rsqueak
fi

if [ "`basename $PWD`" = "compare" ]; then
    cd squeak
fi


if [ "x$IMAGE" = "x" ]; then
    IMAGE=rsqueak.image
fi

MESSAGE="valuesBench`echo \"$1\" | awk '{print toupper(substr($0,0,1))substr($0,2)}'`"
shift

if [ $# -ge 1 ]; then
    EXTRA="$1"
    shift
    BENCHARGS="-m $MESSAGE -n $EXTRA"
else
    BENCHARGS="-m $MESSAGE"
fi



OS=`uname -s`
if [ "$OS" = "Linux" ]; then
  # ulimit -s 1048576
  export TIME="0:RESULT-mem:kbyte: %M.0"
  DOIT=/usr/bin/time
fi

export PYPY_GC_MIN=1GB
export PYPY_GC_GROWTH=2.5
exec $DOIT $RSQUEAK $ARGS $BENCHARGS $IMAGE "$@"
