#!/bin/sh

ARGS=""
while [ "`expr \"x$1\" : \"x\(.\{2\}\)\"`" = "-A" ]; do
  ARGS="$ARGS `expr \"x$1\" : \"x.\{2\}\(.*\)\"`"
  shift
done

SQUEAK=squeak

if [ "`basename $PWD`" = "compare" ]; then
    cd squeak
fi


IMAGE=squeak.image
FIL="./squeak_$1.st"
shift

OS=`uname -s`
if [ "$OS" = "Linux" ]; then
  # ulimit -s 1048576
  export TIME="0:RESULT-mem:kbyte: %M.0"
  DOIT=/usr/bin/time
fi

exec $DOIT $SQUEAK $ARGS $IMAGE $FIL "$@"
