#!/bin/sh

if [ "`basename $PWD`" = "compare" ]; then
    cd ocaml
fi

OS=`uname -s`
if [ "$OS" = "Linux" ]; then
  ulimit -s 1048576
  export TIME="RESULT-mem: %M"
  DOIT=/usr/bin/time
fi

exec $DOIT ./ocaml_"$@"
